### ISSUE TITLE
Inventory menu not working

### ISSUE THREAD

**Issue by Lbergschneider** [Austin-R418/TARP-Development-Tracker#102]
Can’t navigate the inventory menu, mouse just bounces back to one spot [Clip of issue ](https://clips.twitch.tv/TransparentObservantTubersKlappa-CIH76IXh-QhDuXGa)

**Comment by bobjammer1** [comment]
Hello, 
Sorry about this issue. Have you tried any troubleshooting? I would recommend clearing your FiveM cache and seeing what that does for you.
