### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by TheW4ffleKing** [Austin-R418/TARP-Development-Tracker#104]
**Describe the bug**
On the phone when you call someone i could not hang up the phone, when i pressed the backspace button it did not cancel the call and even when i pressed f1 the phone went away but the ringing tone stayed and when i pulled the phone back up i was still calling someone

**To Reproduce**
1. Open your phone
2. Call someone
3. Try to end the call
4. Fails to end the call

**Expected behavior**
A clear and concise description of what you expected/should have happened.
When pressing backspace or f1 it should end the call

**Screenshots**

**Additional context**

**Comment by Fitzie1414** [comment]
unable to replicate
