### ISSUE TITLE
Audi A4 Quattro

### ISSUE THREAD

**Issue by ItsTheSneakyTurtle** [Austin-R418/TARP-Development-Tracker#107]
**Describe the bug**
The Audi A4 Quattro (or however you spell it) has poor handling. It's like smooth ice cubes sliding across an icy surface.

**To Reproduce**
1. Uh, drive the Audi.

**Expected behavior**
I imagine the handling should be better.

**Screenshots**
N/A

**Additional context**
Can't think of anything else to say really.

**Comment by Fitzie1414** [comment]
Added to handling line fix tracker
