### ISSUE TITLE
Controller key binds confliction

### ISSUE THREAD

**Issue by Q31Ethan** [Austin-R418/TARP-Development-Tracker#108]
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected/should have happened.

**Screenshots**

**Additional context**

So there a multiple different way to turn on your hazards on controller that mess with law enforcement buttons on controller, also the bottom d-pad button while in side vehicle puts on seatbelt which also turns on siren for emergency jobs.

**Comment by Fitzie1414** [comment]
working on scrubbing controls to limit most to keyboard only.
