### ISSUE TITLE
Weather Inconsistencies and Issues

### ISSUE THREAD

**Issue by FurryK1tt3n** [Austin-R418/TARP-Development-Tracker#115]
The weather seems to be different for different people, i.e. for 2 of us it is either constantly raining or so foggy you can't see anything in front of you while the other 2 say its sunny and not raining/foggy at all. The sky also keeps turning green in the daylight then eventually changing to normal. And a few times everything goes almost black and white with just one color showing (either red or blue). It seems to cycle through repeatedly every several minutes. 

![weather issue bug - sept 7 2021](https://user-images.githubusercontent.com/90240361/132297067-5d128ca6-6651-47cd-94f3-50060673cc58.png)

![weather issue bug 2 - sept 7 2021](https://user-images.githubusercontent.com/90240361/132298674-873fc375-da2f-42b3-a977-93d6e23abe95.png)

**Comment by Fitzie1414** [comment]
I think this has been fixed. Will reopen if the issue appears again
