### ISSUE TITLE
Vehicle List

### ISSUE THREAD

**Issue by Limitzzz** [Austin-R418/TARP-Development-Tracker#119]
**Describe the bug**
On the vehicle list when you go to buy the "Comet" and that "Comet 5" in "Sports" the prices and names are switched! the "Comet" on the vehicle list is the actual Comet 5 and it's price is "$65k" but should be $1,145,000. Same thing for the "Comet 5" its actually the Comet and its price is "$1,145,000" but it should be $65k. Just an FYI you should take a closer look at this

**Comment by Fitzie1414** [comment]
Have this one in another ticket as well. Going to close this one, still working on a fix
