### ISSUE TITLE
Random Pistol

### ISSUE THREAD

**Issue by Addoie** [Austin-R418/TARP-Development-Tracker#12]
**Describe the bug**
If you kill a security guard or local cop who has a pistol out, you pickup the pistol but it doesn't appear in your inventory.

**To Reproduce**
1. Find a local cop or security guard
2. Kill them
3. See error

**Expected behavior**
You pickup the pistol and it gets added to your inventory.

**Comment by ItsTheSneakyTurtle** [comment]
This is the same for mercenaries at the port. You can get a rifle.
