### ISSUE TITLE
Invisible people

### ISSUE THREAD

**Issue by MADDHATTR3SS** [Austin-R418/TARP-Development-Tracker#21]
**Describe the bug**
There is a known issue with apartments regarding the inventory stash. However there is also an issue that when signing off or losing connection in an apartment you become invisible to everyone but yourself. You must re-enter and leave the apartment to fix it. If someone is with you they have to purchase their own apartment to fix the issue.

**To Reproduce**
1. go to apartment
2. Enter 
3. Log out or disconnect
4. Come back in and your invisible
5. This happened during a restart for me.

**Expected behavior**
Wake up and go on with my day lol. Not be Casper the friendly ghost.

**Screenshots**

**Additional context**

**Comment by Fitzie1414** [comment]
This is an issue I have seen with the apartment script on multiple servers. I have yet to find a fix for it other than an Admin teleporting you in and out of an apartment instance.
