### ISSUE TITLE
Tattoos invisible 

### ISSUE THREAD

**Issue by MADDHATTR3SS** [Austin-R418/TARP-Development-Tracker#25]
**Describe the bug**
When applying tattoos you are unable to see them on your body but for a split second. So you aren't really aware what you are buying since there also is no name or description. Once purchased they can not be removed from the tattoo shop as well. D: In addition, I went to the doctor and the tattoos i did purchase disappeared. 
**To Reproduce**
1. Go to tattoo shop
2. Choose a Tattoo
3. Unable to see the tattoo being purchased other than for just a brief moment.
4. Once purchased you can try to remove but it does not allow it.
5. Got to doctor and hit E I think if the doctor is shared with a plastic surgeon and you hit accept it causes the tattoos to disappear.

**Expected behavior**
A clear and concise description of what you expected/should have happened.

**Screenshots**

**Additional context**

**Comment by Fitzie1414** [comment]
Issued has been fixed.

Added a wait after player model loading before script applies tattoos. It is a rather long delay, but is the shortest I could make it will still getting the tattoos to show 100% of the time.

**Comment by Fitzie1414** [comment]
Tattoos are not visible while picking them in the shop

Tattoos are unable to be removed
