### ISSUE TITLE
Air 1 vehicle control menu......... PAIN

### ISSUE THREAD

**Issue by ItsTheSneakyTurtle** [Austin-R418/TARP-Development-Tracker#29]
**Describe the bug**
When flying in the police helicopter and I try to zoom in on the camera it pulls up the vehicle control menu. I know the vehicle control menu is ] but it also mouse scroll up in the helicopter.

**To Reproduce**
1. Get in Air 1
2. Open the camera and scroll up
3. See error

**Expected behavior**
It is expected that the vehicle control menu doesn't open.

**Screenshots**
self-explanatory anyway

**Additional context**
N/A

**Comment by Austin-R418** [comment]
Update keybinds for vehicle controls

**Comment by Fitzie1414** [comment]
Reassigned keybind for vehcontrol. Still uses "]" but does not conflict with helicopter zoom

Added controller support for helicopter zoom - can now zoom in & out using up & down on the d-pad

**Comment by Fitzie1414** [comment]
Pushed to live 20210717
