### ISSUE TITLE
Can't lockpick cop vehicles to steal the contents inside

### ISSUE THREAD

**Issue by ItsTheSneakyTurtle** [Austin-R418/TARP-Development-Tracker#3]
**Describe the bug**
I wanted to lockpick a cop car to the steal the contents inside. When I got to it I wasn't able to do so. It just didn't register the lockpick. I imagine this might be on purpose, but I am not too sure, and personally, I think we should be able to. The rule says we can't steal cop cars and that is enforced, but we should be able to steal the contents inside cop cars.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a cop car with your lock pick.
2. Click on F2 and drag the lockpick to use with the item count being 1.
4. Nothing happens. It doesn't register it.

**Expected behaviour**
It was expected to begin the lockpicking animation to allow me to open the car doors and trunk to search the car.

**Screenshots**
None

**Additional context**
That's all.

**Comment by ItsTheSneakyTurtle** [comment]
Speaking of which, I can't lockpick civ cars either.

**Comment by Austin-R418** [comment]
Dev Note: ESX:UseItem

**Comment by Fitzie1414** [comment]
Cop cars have definitely been lockpicked recently, going to close this one.
