### ISSUE TITLE
Job Issues - Fisherman

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Development-Tracker#31]
Two issues with the Fisherman job where it is not able to be used:
1. No clothing associated with the job - job clothing was red shooting hearing protection, white tshirt, blue jeans, and unskinned shoes.
2. When arrived at the marker for 

**To Reproduce**
1. Go to Boat pickup marker
2. Enter circle, hit 'e' to get boat
3. See error

**Expected behavior**
Appropriate fishing wear for the job while out at sea fishing. Secondly, the job to be fixed and usable.

**Comment by Fitzie1414** [comment]
esx_jobs is a mess. Attempting to fix, but will likely end up replacing most of the jobs.

**Comment by Fitzie1414** [comment]
Consolidated new jobs into single ticket
