### ISSUE TITLE
Job Issues - Fueler

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Development-Tracker#32]
Multiple Issues with Fueler job:
1. No clothing associated with the job - job clothing was red shooting hearing protection, white tshirt, blue jeans, and unskinned shoes.
2. Oil Drum image too large for inventory box
3. Processed Oil image too large for inventory box
4. When in the process of refining oil, the ratio is three oil drums to one refined, if you do not have three then it takes the remaining oil from your inventory.
5. I feel the payout could be better. Currently pays $61/gas barrel. Realistically, the cost of an oil barrel in the last year has been between 73-75. Just food for thought.

1. Obtain Fueler job
2. Mine oil - this area you will see issue 2
3. Refine oil - this area you will see issue 4 

**Expected behavior**
The job functions correctly as is, but adding appropriate clothing and fixing the image issues in the inventory would make the job more appealing to civilians.

**Comment by Fitzie1414** [comment]
esx_jobs is a mess. Attempting to fix, but will likely end up replacing most of the jobs.

**Comment by Fitzie1414** [comment]
Consolidated new jobs into single ticket
