### ISSUE TITLE
Job Issues - Garbageman

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Development-Tracker#33]
**Describe the bug**
The garbage job does not work at all.

**To Reproduce**
1. Obtain Garbage job
2. View map - no blips for job
3. See error

**Expected behavior**
The job to work.

**Additional context**
Prior to edits to the job, a couple updates ago, the job used to work. After getting the job, I went to the area where the job should have spawned at and there were no markers for any clothing spawn, truck spawn, or truck return.

**Comment by Fitzie1414** [comment]
esx_jobs is a mess. Attempting to fix, but will likely end up replacing most of the jobs.

**Comment by Fitzie1414** [comment]
Consolidated new jobs into single ticket
