### ISSUE TITLE
Job Issues - Butcher

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Development-Tracker#34]
**Describe the bug**
Better instruction as to where and how to complete the job. The only blip on the map was the clothing location, first step, and final step in the job. There was no markers for the in-between steps. The factory had all the correct markers in person but they weren't labeled on the map for all to see. 

**To Reproduce**
1. Obtain Butcher job
2. View Map
3. See error

**Expected behavior**
The map to have all the appropriate blips on the map to show the worker where to go to complete the job.

**Comment by Fitzie1414** [comment]
esx_jobs is a mess. Attempting to fix, but will likely end up replacing most of the jobs.

**Comment by Fitzie1414** [comment]
Consolidated new jobs into single ticket
