### ISSUE TITLE
06' Charger Limited Modifications

### ISSUE THREAD

**Issue by MGarrett2120** [Austin-R418/TARP-Development-Tracker#37]
**Describe the bug**
The new 06' Dodge Charger doesn't seem to have any modifications other than primary respray. I have come across others who haven't even been able to paint it. I have run into an issue with the window tint and horns myself.

**To Reproduce**
1. Go to 'mod shop'
2. Click on 'cosmetics'
3. Scroll down to 'horn/windows/etc. and buy an option; Also see no wheel, body part, or tire options'

**Expected behavior**
Certain cosmetics should appear in the list and said cosmetic is to be placed on the vehicle.
**Screenshots**

**Additional context**
Bug seems to vary from player to player.

**Comment by Fitzie1414** [comment]
trying to find the original files. It appears the carvariations is missing
