### ISSUE TITLE
Police Menu Issues

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Development-Tracker#40]
**Describe the bug**
The F6 police menu does not work when fining/charging people. The penal codes and charge amounts are not put in a table or loaded into the table on the backend. After completing step 3 below you should be able to select any of the other options which would open to a list of other fines and such, then you should be able to select a charge to fine the player with.

**To Reproduce**
1. Get police job
2. Click civilian interaction
3. Click Fine
4. See Error

**Expected behavior**
The fines area of the script to work.

**Comment by Fitzie1414** [comment]
DB table fine_types is missing. Working on building it on the dev side

**Comment by Fitzie1414** [comment]
DB table has been built. There aren't a lot of fines in the penal code....

Will need assistance testing

**Comment by Fitzie1414** [comment]
Fines can now be properly issued

**Comment by theblitz1738** [comment]
@Fitzie1414 I'm reopening this because I think it's an issue, but the fine money goes straight to bank account of the Trooper or whoever is writing the citation. I don't know if the job has a bank account or money is even an issue but I don't think the money should go to the Troopers who write them, may cause a bit of a precarious situation.

**Comment by Austin-R418** [comment]
Police Society Fund

**Comment by Fitzie1414** [comment]
Fixed? - Needs testing

Set Config.EnablePlayerManagement to true, should now deposit fine payments into the society fund.
