### ISSUE TITLE
Police Cruiser Emergency lights

### ISSUE THREAD

**Issue by brookins2013** [Austin-R418/TARP-Development-Tracker#53]
**Describe the bug**
The lights on the cruiser are extremely dim to the point you can almost not see them. People that have graphic mods say they are fine but everything was working for me yesterday 7/6/21 before that cray glitch around 11pmEST. 

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected/should have happened.

**Screenshots**

![A7A1583C-12B1-459A-BABC-2A258B63EFC4](https://user-images.githubusercontent.com/85260934/124861039-c0e56880-df80-11eb-8655-0cc29bf82804.jpeg)

![4442D047-EC02-4233-A339-57DC2F85E3F6](https://user-images.githubusercontent.com/85260934/124861061-cd69c100-df80-11eb-8a74-27ad73793f38.jpeg)

two different cruisers, two different troopers with two different computers 

**Additional context**

**Comment by Austin-R418** [comment]
Thank you for reporting this.

We are aware that this has happened, and it is not a bug. The server used to stream a server sided visual settings mod, we removed that mod so clients could choose which graphics mods they wanted to use. Later on today when I’m not at work I will post a few free options and an explanation on how to install them. 

Not everyone like the same style of graphics, so we want you, the player, to choose what looks best for you.

**Comment by brookins2013** [comment]
Oh ok. Awesome thanks for letting me know. I was driving myself crazy trying to figure out what happened. I download a mod earlier and it seems to be working
