### ISSUE TITLE
tow script issues

### ISSUE THREAD

**Issue by voltrox910** [Austin-R418/TARP-Development-Tracker#55]
the mechanic missions conflict with controller users when y is pressed
also when using the left joystick the bed goes up and down

**Comment by Fitzie1414** [comment]
fixed mechanic job keybind issue - will only accept input from keyboard now

Unable to fix flatbed keybind issue - Opening support ticket with original creator

**Comment by Fitzie1414** [comment]
Mechanic keybind fix pushed to live server 20210713
