### ISSUE TITLE
/steal bug

### ISSUE THREAD

**Issue by RonRuncles** [Austin-R418/TARP-Development-Tracker#58]
When I try to /steal as a state trooper to search, my character freezes up every time and I can't move, I have to relog to fix this. I don't have a screenshot as it would just be me standing somewhere. Unsure if this is a persistent issue within or just me

**Comment by Addoie** [comment]
I  used the /steal command multiple times tonight and did not have any issues.

**Comment by MyLifeAsRK3** [comment]
I also just tried this in both the dev and main server environments with no isses.  Please clear your cache and if the issue persists, let us know.
