### ISSUE TITLE
Local Doctor

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Development-Tracker#59]
**Describe the bug**
The circle for the local doctor is not working. I went to Pillbox and Sandy Springs and neither location have the local doctor treatment option. If you got a distance away from the circle you could see it on the ground but when you approached it would disappear. This periodically works and doesn't work. I know @Austin-R418 had to reset it several times last night while in the server for it to work.

**To Reproduce**
1. Go to local hosptial
2. Attempt to find blip or be treated by doctor
3. See error

**Expected behavior**
The local doctor to treat you.

**Comment by Austin-R418** [comment]
Issue with doctor resolved. We need to move the locations for the
