### ISSUE TITLE
Sandy Car Shop

### ISSUE THREAD

**Issue by Austin-R418** [Austin-R418/TARP-Development-Tracker#69]
Vehicle store in Sandy shores for Civilians

**Comment by theblitz1738** [comment]
@Austin-R418 get a hold of @Fitzie1414 because I know he has a script for one in Harmony. It's at the actual car dealership in Harmony next to the clothing store and across from the gas station.

**Comment by Fitzie1414** [comment]
Added a car shop in Harmony. 

Currently it has the same vehicles available as the city carshop. We can change this in the future, but will require some database updates.

new files: esx_advancedvehicleshopsandy
