### ISSUE TITLE
Twitter Account Issues

### ISSUE THREAD

**Issue by ItsTheSneakyTurtle** [Austin-R418/TARP-Development-Tracker#7]
**Describe the bug**
Twitter accounts don't sync to your multicharacter. I posted on Twitter on my cop character and it used my criminal character.

**To Reproduce**
Uh... post on twitter.

**Expected behavior**
I expected the Twitter to be 'TrooperTurtle', instead, it was 'Ratcliffe'

**Screenshots**
https://prnt.sc/143abri

**Additional context**
n/a

**Comment by Austin-R418** [comment]
Thank you for reporting this bug. I have not played on the actual server yet so I am not entirely sure how a lot of the old scripts work. Could you please tell me if you have to log into your twitter account or is it automatically logged in when you log in.

**Comment by ItsTheSneakyTurtle** [comment]
> Thank you for reporting this bug. I have not played on the actual server yet so I am not entirely sure how a lot of the old scripts work. Could you please tell me if you have to log into your twitter account or is it automatically logged in when you log in.

It is automatically logged in. I do have two Twitter accounts for the server from what I remember but once I select my character it is automatically logged into Twitter. Sometimes it is on the correct Twitter profile and sometimes it isn't.

**Comment by Austin-R418** [comment]
Ok. I’ll take a look. Shouldn’t be too hard to fix the issue.
