### ISSUE TITLE
Peace Time

### ISSUE THREAD

**Issue by Austin-R418** [Austin-R418/TARP-Development-Tracker#72]
Peace Time script and fix the postal codes on the hud. Also make the hud open when your fist log in so you dont have to type /toggleui twice to get it up.

**Comment by Fitzie1414** [comment]
Haven't pushed the update yet, but increased the number of police required for certain robberies. Getting the ATM Robberies working then will push it as a new heist update.

Trouble shooting the HUD

Will need to search around to see if I can find a more indepth peacetime script
