### ISSUE TITLE
Loading screen black & White also shows awaiting script

### ISSUE THREAD

**Issue by JordonEdits** [Austin-R418/TARP-Development-Tracker#73]
So i loaded into the server and my screen is now black & white but it also shows in the bottom right hand corner Awaiting Scripts but then in the bottom left it shows how many mods I have loaded what do I do 

Proof: https://gyazo.com/051f61572ea393390784820e071f7bcd

**Comment by Fitzie1414** [comment]
Quit and load back in.

**Comment by Fitzie1414** [comment]
Issue resolved

Client side ENB issue
