### ISSUE TITLE
GMC 

### ISSUE THREAD

**Issue by Jkelley6616** [Austin-R418/TARP-Development-Tracker#76]
The gmc doesn't spawn a license plate. At the very least, cops shouldn't be able to pull you over for it.

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected/should have happened.

**Screenshots**

**Additional context**

**Comment by Fitzie1414** [comment]
Which GMC is this?

**Comment by Jkelley6616** [comment]
The jacked up sierra
