### ISSUE TITLE
New CIV Jobs

### ISSUE THREAD

**Issue by Fitzie1414** [Austin-R418/TARP-Development-Tracker#79]
esx_brinksjob - Armored Car Driver (No markers)

esx_busjob - Bus driver

esx_cityworks - Public Works job (THIS ONE WORKS)

esx_constructor - Construction Worker (Can't set player to job)

esx_garbagecrew - Multiple person garbage crew (needs testing with multiple people)

esx_gopostal - Postal Driver (Markers won't show up)

esx_poolcleaner - Pool Boy (Works, but uniforms need fixing)

esx_truckerjob - Truck driver (Markers not showing)

**Comment by Fitzie1414** [comment]
Jobs to keep from esx_jobs:
- Lumberjack
- Miner
- Taxi

Others are not working

Also need to add Security Job & McDonalds job to job & job_grades in database so they are accessible from the Job Center

**Comment by theblitz1738** [comment]
esx_poolcleaner job updated, tested, completed. 
Change log: 
- activated job in server database
- Switched vehicle to utility vehicle
- Removed uniform requirements
- Moved menu ui to top left
- Added receipt icon

**Comment by Fitzie1414** [comment]
Pool Cleaner & City Works Pushed to live 20210724
