### ISSUE TITLE
Tackle Script

### ISSUE THREAD

**Issue by Fitzie1414** [Austin-R418/TARP-Development-Tracker#86]
Port over tackle script from old files

**Comment by Fitzie1414** [comment]
Added to Dev server, need victim... i mean tester

**Comment by Austin-R418** [comment]
The tackle script that was on the dev box is working. I fixed it. 

When you are sprinting and hit E you will tackle the person.

**Comment by Fitzie1414** [comment]
I'll test them both out. I know the one I used to use has a pretty nice animation.

**Comment by Fitzie1414** [comment]
Pushed to live 20210724
