### ISSUE TITLE
Admin Updates

### ISSUE THREAD

**Issue by Fitzie1414** [Austin-R418/TARP-Development-Tracker#88]
-Moderator Permission: Spectate, Kick, Freeze/Unfreeze

Priority Timer (Bobby is working on one that goes off the individual, will put global in as a placeholder)

**Comment by Austin-R418** [comment]
Make sure the priority script is integrated with the trew_hud

**Comment by Austin-R418** [comment]
Once I’m back I’m going to fix the issues with the postal codes on it.
