### ISSUE TITLE
Random shotgun

### ISSUE THREAD

**Issue by ItsTheSneakyTurtle** [Austin-R418/TARP-Development-Tracker#9]
**Describe the bug**
After holstering certain items I always end up with a shotgun in my hands. It has happened to a few people.

**To Reproduce**
1. Have a hotbar item equipped.
2. Put it away in which I sometimes equip another item.
3. It should give you a shotgun when holstered.

**Expected behavior**
I don't expect a shotgun. lol

**Screenshots**
https://prnt.sc/149bzqz

**Additional context**
I have no idea why I get it.

**Comment by Austin-R418** [comment]
Did you recently get out of a Police Car when that was given to you?

**Comment by Austin-R418** [comment]
Ok. The issue is within the police vehicles automatically giving them. The issue has been passed along to the asset team and Dylan will get it fixed soon.

**Comment by Austin-R418** [comment]
> Yes, often in the space of about 10 minutes after leaving a police vehicle, when I try to holster an item it equips the shotgun.

Could you please Clarify what police vehicle you were using when this happened. We noticed an issue with the K9 vehicles but not with any others.

**Comment by ItsTheSneakyTurtle** [comment]
> > Yes, often in the space of about 10 minutes after leaving a police vehicle, when I try to holster an item it equips the shotgun.
> 
> Could you please Clarify what police vehicle you were using when this happened. We noticed an issue with the K9 vehicles but not with any others.

I was using the unmarked Mustang and the 2016 Explorer.

**Comment by ItsTheSneakyTurtle** [comment]
Dunno if this helps. http://i.prntscr.com/mHSwDLi2TumriuUyneP2GA.png
