### ISSUE TITLE
Car Dealership Menu Issue

### ISSUE THREAD

**Issue by Necronachos** [Austin-R418/TARP-Development-Tracker#90]
I haven’t tried the Sandy Shores dealer yet, but In the city when you go to buy a vehicle the moment you press the down button on your keyboard it will pull up the next available car and take away the menu and you will be stuck. Duplicated by re-logging and trying again.

**Comment by theblitz1738** [comment]
Can confirm this does happen in Live Server but not in Development server.

**Comment by Fitzie1414** [comment]
Double check this after restart, it was working when I fixed it earlier, but maybe something changed

**Comment by JordonEdits** [comment]
can confirm this does happen still its happening to me right now

**Comment by theblitz1738** [comment]
The error exists in the PDM Shop, the city car dealership. However, Larry's RV Sales, harmony dealership, does work.
