### ISSUE TITLE
2.3 Update Issues

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Development-Tracker#91]
- [x] - Controller keybind issue -> Down on D-Pad opens player medical menu while on foot, near other player opens their menu, and while in vehicle for emergency services it activates siren and opens player menu

- [ ] - "Public works does not give you the bonus for the jobs you do" -- unconfirmed

- [ ] Can tackle through bars in the police holding cell area

Mcdonald's Job Issues:

- [ ] - Cashier gets stuck and cannot pass the "get customer meal" -> "citizen:/scripting/lua/scheduler.lua:1145: No such export DoHudText in resource mythic_notify"

- [ ] - Deliver driver cannot pickup meal for delivery and gets stuck cannot pass -> "citizen:/scripting/lua/scheduler.lua:1145: No such export DoHudText in resource mythic_notify"

**Comment by Fitzie1414** [comment]
Confirm Public Works issues the checks (may need to add the item to the inventory (oops))
Medical Menu is also reportedly not opening for other players with Alt-Z

**Comment by Fitzie1414** [comment]
JK, medical menu works. It was a client side issue

**Comment by theblitz1738** [comment]
Mcdonald's Job Issues:
- Top right name too long, word wrap into cash $ line
- Cashier position gets stuck and cannot pass the "get customer meal"

**Comment by theblitz1738** [comment]
Can tackle through bars in the police holding cell area
