### ISSUE TITLE
Can’t buy vehicle.

### ISSUE THREAD

**Issue by Lbergschneider** [Austin-R418/TARP-Development-Tracker#92]
**Describe the bug**
**To Reproduce**
1. Go to buy a vehicle.
2. Try to change the vehicle category
3. Wait for new vehicle to load
4. Menu disappears can’t exit shop or change vehicles.

**Expected behavior**
A clear and concise description of what you expected/should have happened.
I attempted to buy a car and when I went to change the category it would attempt to load a new vehicle and then the menu disappears and I can’t back out of the shop menu.
**Screenshots**

**Additional context**

**Comment by Fitzie1414** [comment]
Fixed. For some reason it was trying to load a pickup truck as a boat?

Split the car shop and boat shot into separate resources
