### ISSUE TITLE
Controller button needs remaped

### ISSUE THREAD

**Issue by Lbergschneider** [Austin-R418/TARP-Development-Tracker#94]
**Describe the bug**
Pressing down on the controller d-pad triggers police siren and personal health menus
**To Reproduce**
1. Go to police vehicle 
2. Click on down key on controller d-pad
3. Police siren turns on but so does health menu

**Expected behavior**
A clear and concise description of what you expected/should have happened.
Down on dpad should just trigger sirens
**Screenshots**

**Additional context**

**Comment by theblitz1738** [comment]
Closed - medical menu key was mapped to ~ (tilda key) and ALT+~
