### ISSUE TITLE
Mcdonalds Job

### ISSUE THREAD

**Issue by dbarnett2912** [Austin-R418/TARP-Development-Tracker#95]
**Describe the bug**
You can choose job at job center but once you go to the mcdonalds to start working it wont let you select a position under the job listing for mcdonalds. The choices are "Cleaner/Off duty" "cashier" "cook" "delivery Driver" It wont let me select any of them

**To Reproduce**
1. Go to 'mcdonalds'
2. Click on 'job listing'
3. Scroll down to 'try and select position to work'

**Expected behavior**
I should be able to enter a job position and start working?

**Comment by theblitz1738** [comment]
@dbarnett2912 please see #91 for the issues with the mcdonalds job and updates will be posted there.
