### ISSUE TITLE
EMS Garage

### ISSUE THREAD

**Issue by dbarnett2912** [Austin-R418/TARP-Development-Tracker#96]
**Describe the bug**
Unable to spawn ambo from EMS garage. Also when you go to buy a new one to try and get one to spawn that way it still doesn't work

**To Reproduce**
1. Go to 'EMS garage'
2. Click on 'Open garage'
3. Nothing happens

**To Reproduce**
1. Go to 'EMS garage'
2. Click on 'Vehicle Shop'
3. Scroll to any vehicle to purchase
4. Try purchasing vehicle and nothing happens

**Expected behavior**
Should be able to go into garage to spawn a vehicle and or go into vehicle to buy a vehicle.

**Comment by theblitz1738** [comment]
Solved with esx_advancedvehicleshop modification.
