### ISSUE TITLE
impound error

### ISSUE THREAD

**Issue by grimgym** [Austin-R418/TARP-Development-Tracker#97]
**Describe the bug**
When you go to get your car out if the impound it says there is something blocking it but when i go yo look there is nothing there 
**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected/should have happened.
i was trying to get my vehicle out of the impound when it said there is something blocking the spawn 
**Screenshots**

**Additional context**

**Comment by theblitz1738** [comment]
@grimgym Which impound did this occur at? 

Some impounds have different car spawn locations and it may be blocked by a player of local vehicle or person.

**Comment by grimgym** [comment]
it was the sandy impound there was nothing blocking the spawn point
